In [1]:
import torch

In [2]:
def to_onehot(y, num_classes):
    y_onehot = torch.zeros(y.size(0), num_classes)
    y_onehot.scatter_(1, y.view(-1, 1).long(), 1).float()
    return y_onehot

In [4]:
y = torch.tensor([0, 1, 2, 2])
y_enc = to_onehot(y, 3)
print(f"one_hot encoding: {y_enc}")

one_hot encoding: tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.]])


In [5]:
tensor0d = torch.tensor(1)
tensor1d = torch.tensor([1, 2, 3])
tensor2d = torch.tensor([[1, 2], [3, 4]])
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [6]:
tensor0d

tensor(1)

In [7]:
tensor1d, tensor2d, tensor3d

(tensor([1, 2, 3]),
 tensor([[1, 2],
         [3, 4]]),
 tensor([[[1, 2],
          [3, 4]],
 
         [[5, 6],
          [7, 8]]]))

In [8]:
import torch.nn.functional as F

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2])
b = torch.tensor([0.0])
z = x1 * w1 + b
a = torch.sigmoid(z)
loss = F.binary_cross_entropy(a, y)

In [9]:
loss

tensor(0.0852)

In [10]:
z, a

(tensor([2.4200]), tensor([0.9183]))

In [11]:
a, y, a-y

(tensor([0.9183]), tensor([1.]), tensor([-0.0817]))

In [12]:
from torch.autograd import grad

In [13]:
y, x1

(tensor([1.]), tensor([1.1000]))

In [15]:
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

In [16]:
z = w1 * x1 + b
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)

In [17]:
grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)

In [18]:
grad_L_w1, grad_L_b

((tensor([-0.0898]),), (tensor([-0.0817]),))

In [19]:
loss

tensor(0.0852, grad_fn=<BinaryCrossEntropyBackward0>)

In [20]:
loss.backward()
print(w1.grad)
print(b.grad)

tensor([-0.0898])
tensor([-0.0817])


In [27]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()

        self.layers = torch.nn.Sequential(

            # 1st hidden layer
            torch.nn.Linear(num_inputs, 30),
            torch.nn.ReLU(),

            # 2nd hidden layer
            torch.nn.Linear(30, 20),
            torch.nn.ReLU(),

            # output layer
            torch.nn.Linear(20, num_outputs),
        )
    
    def forward(self, x):
        logits = self.layers(x)
        return logits
    

In [28]:
model = NeuralNetwork(50, 3)
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


In [29]:
model.layers

Sequential(
  (0): Linear(in_features=50, out_features=30, bias=True)
  (1): ReLU()
  (2): Linear(in_features=30, out_features=20, bias=True)
  (3): ReLU()
  (4): Linear(in_features=20, out_features=3, bias=True)
)

In [31]:
type(model.parameters)

method

In [32]:
type(model.parameters())

generator

In [39]:
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Total number of trainable model parameters: {num_params}")

Total number of trainable model parameters: 2213


In [40]:
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.1369, -0.1177,  0.0139,  ..., -0.1392,  0.0256, -0.1251],
        [ 0.0941, -0.0799, -0.0615,  ...,  0.0756,  0.0862, -0.0270],
        [ 0.0697, -0.1087, -0.0395,  ..., -0.1171,  0.1240,  0.1315],
        ...,
        [-0.0572,  0.0346, -0.0139,  ..., -0.0102, -0.1112,  0.0700],
        [-0.0441, -0.0910, -0.0241,  ...,  0.0639, -0.0080,  0.0667],
        [-0.0030, -0.0967,  0.1049,  ..., -0.1294,  0.0177,  0.0282]],
       requires_grad=True)


In [41]:
print(model.layers[0].weight.shape)

torch.Size([30, 50])


In [42]:
print(model.layers[0].bias)

Parameter containing:
tensor([ 0.1085,  0.0221, -0.0652,  0.0336, -0.0510, -0.1134,  0.1050,  0.1027,
        -0.1221, -0.0465,  0.0167, -0.0691,  0.1368, -0.1323,  0.0701,  0.0455,
        -0.0142, -0.0700,  0.1296, -0.0761,  0.0140,  0.0980,  0.0918,  0.0649,
        -0.1235,  0.0496, -0.1154,  0.0793, -0.0932, -0.0532],
       requires_grad=True)


In [43]:
torch.manual_seed(123)
model = NeuralNetwork(50, 3)
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)


In [44]:
X = torch.rand((1, 50))
out = model(X)
print(out)

tensor([[-0.1670,  0.1001, -0.1219]], grad_fn=<AddmmBackward0>)


In [45]:
model.forward(X)

tensor([[-0.1670,  0.1001, -0.1219]], grad_fn=<AddmmBackward0>)

In [46]:
with torch.no_grad():
    out = model(X)
print(out)

tensor([[-0.1670,  0.1001, -0.1219]])


In [47]:
with torch.no_grad():
    out = torch.softmax(model(X), dim=1)
print(out)

tensor([[0.2983, 0.3896, 0.3121]])


In [48]:
X_train = torch.tensor([
    [-1.2, 3.1],
    [-0.9, 2.9],
    [-0.5, 2.6],
    [2.3, -1.1],
    [2.7, -1.5]
])
y_train = torch.tensor([0, 0, 0, 1, 1])

X_test = torch.tensor([
    [-0.8, 2.8],
    [2.6, -1.6],
])
y_test = torch.tensor([0, 1])


In [49]:
from torch.utils.data import Dataset

In [50]:
class ToyDataset(Dataset):
    def __init__(self, X, y):
        self.features = X
        self.labels = y

    def __getitem__(self, index):
        one_x = self.features[index]
        one_y = self.labels[index]
        return one_x, one_y
    
    def __len__(self):
        return self.labels.shape[0]

train_ds = ToyDataset(X_train, y_train)
test_ds = ToyDataset(X_test, y_test)


In [51]:
train_ds

In [52]:
train_ds[1]

(tensor([-0.9000,  2.9000]), tensor(0))

In [53]:
len(train_ds)

5

In [54]:
from torch.utils.data import DataLoader

In [55]:
torch.manual_seed(123)

In [56]:
train_loader = DataLoader(
    dataset = train_ds,
    batch_size = 2,
    shuffle = True,
    num_workers = 0
)

test_loader = DataLoader(
    dataset = test_ds,
    batch_size = 2,
    shuffle = False,
    num_workers = 0
)

In [57]:
for idx, (x, y) in enumerate(train_loader):
    print(f"Batch {idx + 1}:", x, y)

Batch 1: tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]]) tensor([1, 0])
Batch 2: tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]]) tensor([0, 0])
Batch 3: tensor([[ 2.7000, -1.5000]]) tensor([1])


In [58]:
# Training loader drops the last batch

train_loader = DataLoader(
    dataset = train_ds,
    batch_size = 2,
    shuffle = True,
    num_workers = 0,
    drop_last = True
)

In [59]:
for idx, (x, y) in enumerate(train_loader):
    print(f"Batch {idx + 1}:", x, y)

Batch 1: tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]]) tensor([0, 0])
Batch 2: tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]]) tensor([1, 0])


In [60]:
F

<module 'torch.nn.functional' from '/home/slowstepper/Documents/projects/python/llms-scratch/.venv/lib/python3.10/site-packages/torch/nn/functional.py'>

In [64]:
torch.manual_seed(123)
model = NeuralNetwork(num_inputs=2, num_outputs=2)
optimizer = torch.optim.SGD(
    model.parameters(), lr = 0.5
)

In [65]:
num_epochs = 3
for epoch in range(num_epochs):
    
    model.train()
    for batch_idx, (features, labels) in enumerate(train_loader):
        logits = model(features)
        loss = F.cross_entropy(logits, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        ### LOGGING
        print(f"Epoch: {epoch + 1:03d}/{num_epochs:03d}"
              f" | Batch {batch_idx:03d}/{len(train_loader):03d}"
              f" | Train Loss: {loss:.2f}")
        
    model.eval()

Epoch: 001/003 | Batch 000/002 | Train Loss: 0.75
Epoch: 001/003 | Batch 001/002 | Train Loss: 0.65
Epoch: 002/003 | Batch 000/002 | Train Loss: 0.44
Epoch: 002/003 | Batch 001/002 | Train Loss: 0.13
Epoch: 003/003 | Batch 000/002 | Train Loss: 0.03
Epoch: 003/003 | Batch 001/002 | Train Loss: 0.00


In [66]:
model.eval()
with torch.no_grad():
    outputs = model(X_train)
print(outputs)

tensor([[ 2.8569, -4.1618],
        [ 2.5382, -3.7548],
        [ 2.0944, -3.1820],
        [-1.4814,  1.4816],
        [-1.7176,  1.7342]])


In [67]:
torch.set_printoptions(sci_mode=False)
probas = torch.softmax(outputs, dim=1)
print(probas)

tensor([[    0.9991,     0.0009],
        [    0.9982,     0.0018],
        [    0.9949,     0.0051],
        [    0.0491,     0.9509],
        [    0.0307,     0.9693]])


In [68]:
predictions = torch.argmax(outputs, dim=1)
print(predictions)

tensor([0, 0, 0, 1, 1])


In [71]:
def compute_accuracy(model, dataloader):

    model = model.eval()
    correct = 0.0
    total_examples = 0

    for idx, (features, labels) in enumerate(dataloader):

        with torch.no_grad():
            logits = model(features)

        predictions = torch.argmax(logits, dim=1)
        compare = (labels == predictions)
        correct += torch.sum(compare)
        total_examples += len(compare)
    
    return (correct / total_examples).item()






In [72]:
print(compute_accuracy(model, train_loader))

1.0


In [73]:
print(compute_accuracy(model, test_loader))

1.0


In [74]:
torch.save(model.state_dict(), "model.pth")

In [76]:
model = NeuralNetwork(2, 2)
model.load_state_dict(torch.load("model.pth", weights_only=True))

<All keys matched successfully>